// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY3UYSoMSc23L-pwP6X50lJrr7UJvWZS8',
    appId: '1:107934070021:web:09875863578b90da10336c',
    messagingSenderId: '107934070021',
    projectId: 'loginsignup-10769',
    authDomain: 'loginsignup-10769.firebaseapp.com',
    storageBucket: 'loginsignup-10769.firebasestorage.app',
    measurementId: 'G-0TFPSWC30F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgvToBUpnIJd9cOBsp5HQUKNXRL0IohxM',
    appId: '1:107934070021:android:933247dd9a74a71810336c',
    messagingSenderId: '107934070021',
    projectId: 'loginsignup-10769',
    storageBucket: 'loginsignup-10769.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaSbjYvAmfVrGTOVvb7c5n-WbA1DmYBNg',
    appId: '1:107934070021:ios:6f1688ff8d24f3e710336c',
    messagingSenderId: '107934070021',
    projectId: 'loginsignup-10769',
    storageBucket: 'loginsignup-10769.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );
}
